version: '3'
services:
  # Pythonアプリケーション用のコンテナ
  python:
    build: .
    volumes:
      - ./app:/app # ローカルのappディレクトリをコンテナ内の/appにマウント
    env_file:
      - .env # .envファイルから環境変数を読み込む
    environment:
      - TZ=Asia/Tokyo
      - TACHIBANA_USERID=fps04170
      - TACHIBANA_PASSWORD=1997805d
      - TACHIBANA_PASSWORD2=1381
    depends_on:
      - db # コンテナ起動前にdbサービスが起動するのを待機
    command: sleep infinity # コンテナが停止しないように無限ループで待機

  # PostgreSQLデータベース用のコンテナ
  db:
    image: postgres:13
    env_file:
      - .env # .envファイルから環境変数を読み込む
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data # データ永続化のためにデータボリュームをマウント
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 初期化スクリプトをマウントして初期化時に実行
    ports:
      - "5432:5432" # ポート5432を公開
volumes:
  postgres_data: # PostgreSQLのデータボリューム
